name: Build manual linux appimage - test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
      tags:
        description: 'Build manual Linux AppImage - Test'

env:
  QT_SELECT: 5
  QT_VERSION: '5.15.2' # quotes required or YAML parser will interpret as float

# The tag name is Test-weekly-YYmmdd-HHMM to enable multiple tests per day
jobs:

  release-data:
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create-release-data.outputs.upload_url }}

    steps:
      - name: create name and tag
        id: create-name-and-tag
        run: |
          echo "TAG_NAME=Test-manual-`date +"%F%H%M"`" >> $GITHUB_ENV
          echo "RELEASE_NAME=Test manual `date +"%F%H%M"`" >> $GITHUB_ENV
          echo "CUR_DIR=$PWD" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create release data
        id: create-release-data
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: Manual test of linux appimage build, creates pre-release
          draft: false
          prerelease: true

  linux:
    runs-on: ubuntu-20.04
    needs: release-data
    env:
      UPLOAD_URL: "${{ needs.release-data.outputs.upload_url }}"

    steps:
      - name: checkout code
        uses: actions/checkout@v2.4.2
        with:
          submodules: true
          fetch-depth: 0        

      - name: install kde and build dependencies
        run: |  
          # *********************************
          echo "-- install qt 5.15.2 --"
          sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-focal          
          sudo apt update           
          
          # *********************************
          echo "-- register kde neon repository --"
          sudo apt install -y debsig-verify           
          echo 'deb http://archive.neon.kde.org/user focal main' | sudo tee /etc/apt/sources.list.d/neon.list
          curl https://origin.archive.neon.kde.org/public.key -o - | sudo apt-key add - 
          
          # *********************************
          echo "-- install build dependencies --"
          sudo apt install -y build-essential gettext git qt5-default qttools5-dev libqt5svg5-dev libqt5xmlpatterns5-dev
          sudo apt install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
        
      - name: build Seamly2D & SeamlyMe
        run: |
          # *********************************
          echo "-- show current directory --"
          pwd
          echo "-- find the .rcc files recursively, before building Seamly2D & SeamlyMe-- "
          ls -Rla ./src/app | grep '\.rcc$' | wc -l
                    
          # *********************************
          echo "-- make Seamly2D & SeamlyMe --"
          qmake PREFIX=/usr Seamly2D.pro -r CONFIG+=no_ccache
          make -j$(nproc) && make install
          
          # *********************************
          echo "-- remove & recreate AppDir --"
          sudo rm -rf AppDir || true
          sudo mkdir -v AppDir
          
          # *********************************
          echo "-- create AppDir usr/share directories--"
          sudo mkdir -p AppDir/usr/share/translations
          sudo mkdir -p AppDir/usr/share/applications
          sudo mkdir -p AppDir/usr/share/icons/hicolor/64x64/apps
          sudo mkdir -p AppDir/usr/share/icons/hicolor/256x256

      - name: compile diagramqrc to diagramrcc
        id: compile-diagramqrc-to-diagramrcc
        run: |
          # ********************************************
          echo " --- compile src/app/seamlyme/share/resources/diagrams.qrc to src/app/seamlyme/share/resources/diagrams.rcc ---"
          rcc -no-compress -binary src/app/seamlyme/share/resources/diagrams.qrc -o src/app/seamlyme/share/resources/diagrams.rcc

          # ********************************************
          echo "-- find the .rcc files recursively, after compiling diagrams.rcc "
          ls -Rla ./src/app/seamlyme/share | grep '\.rcc$' | wc -l   && echo "--- END COMPILE DIAGRAM.QRC TO DIAGRAM.RCC ---"     

      - name: copy resource files
        id: copy-resource-files
        run: |
          echo "_______BEGIN DEBUGGING ___________________________"
          #********************************************
          # when copying files we get this error: 
          # ls: cannot access 'AppDir/usr/share/diagrams.rcc': No such file or directory
          # cp: cannot stat 'src/app/seamlyme/bin/diagrams.rcc': No such file or directory

          #********************************************
          echo "-- show the current directory and list files --"
          echo "------ then list files in the src/app subdirectory --"
          pwd && ls -la && ls -la ./src/app

          #********************************************
          echo "-- find the .rcc files recursively -- "
          ls -Rla ./src/app/seamlyme/share/ | grep '\.rcc$' && echo "_______END DEBUGGING ___________________________"
          
          #********************************************
          echo "-- copy measurement diagrams.rcc file from new location --"
          #cp src/app/seamlyme/bin/diagrams.rcc AppDir/usr/share
          sudo cp src/app/seamlyme/share/resources/diagrams.rcc AppDir/usr/share
          
          #********************************************
          echo "-- copy translation *.qm files --"
          sudo cp share/translations/*.qm AppDir/usr/share/translations
          
          #********************************************
          echo "-- copy .desktop files --"
          sudo cp dist/seamly2d.desktop AppDir/usr/share/applications
          sudo cp dist/seamlyme.desktop AppDir/usr/share/applications
          
          #********************************************
          echo "-- copy icon .png files --"
          sudo cp dist/seamly2d.png AppDir/usr/share/icons/hicolor/64x64/apps/
          sudo cp share/img/Seamly2D_logo_256x256.png AppDir/usr/share/icons/hicolor/256x256/seamly2d.png 
        
      - name: build Seamly2D appimage
        # uses parameters from appimage-builder-recipe.yml to build appimage
        # Seamly2D-continuous-x86_64.AppImage
        run: |
          #********************************************
          echo "-- get appimage-builder --"
          #sudo wget -q https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage -O /usr/local/bin/appimage-builder
          sudo wget -q https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage -O /usr/local/bin/appimage-builder
          sudo chmod +x /usr/local/bin/appimage-builder
          
          #********************************************
          echo "-- run appimage-builder with appimage-builder-recipe-test.yml --"
          appimage-builder --recipe dist/appimage-builder-recipe-test.yml --log DEBUG --generate --skip-test

      - name: copy to final file tag_name
        run: |
          #********************************************
          echo "-- find the Seamly2D appimage file & rename it --"        
          ls Seamly2D-continuous-x86_64.AppImage
          sudo mv ./Seamly2D-continuous-x86_64.AppImage ./Seamly2D-x86_64.AppImage

      - name: upload seamly2d-x86_64.tar.gz artifact
        # upload ./Seamly2D-x86_64.AppImage as artifact to Github Workflows
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Seamly2D-x86_64.AppImage
          path: './*AppImage*'

      - name: find file path
        id: path-lister
        uses: Rishabh510/Path-lister-action@1.0
        with:
          path: "."
          type: ".AppImage"

      - name: show file path
        run: |
          #********************************************
          echo "-- show current directory --"          
          pwd
          echo "Found ${{ steps.path-lister.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.path-lister.outputs.paths }}; do
          echo $i
          done

      - name: upload file as pre-release
        # uploads seamly2d-x86_64.tar.gz as pre-release to Github Releases
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./Seamly2D-x86_64.AppImage
          asset_name: ./Seamly2D-x86_64.AppImage
          asset_content_type: application/octet-stream
